[package]
name = "crow"
version = "0.1.0"
authors = ["lcnr/Bastian Kauschke <bastian_kauschke@hotmail.de>"]
edition = "2018"

[dependencies]
gl = "0.14"
glutin = "0.21"
image = "0.22"
static_assertions = "1"

[dev-dependencies]
rand = "0.7"

[[test]]
name = "test"
harness = false